Repository ducktors/turborepo-remote-cache, pull requests merged in 2024-11, with the labels that each got.

#445 fix: Use BODY_LIMIT when creating app
  src/index.ts
Labels: enhancement, automerge

#474 fix: update fastify and plugins to 5.0
  package.json
  pnpm-lock.yaml
  src/logger.ts
Labels: dependencies

#480 fix: logger options only accepts a configuration object #479
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/test.yaml
  README.md
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/logger.ts
Labels: bug

#483 fix: update node on dockerfile
  .github/workflows/fly-deploy.yml
  .nvmrc
  Dockerfile
  README.md
  fly.toml
  package.json
  pnpm-lock.yaml
  src/plugins/remote-cache/routes/get-status.ts
  test/local.ts
Labels: automerge

#484 docs: Update instructions for caching with Docker
  docs/custom-remote-caching.md
Labels: documentation
