Repository ducktors/turborepo-remote-cache, pull requests merged in 2025-02, with the labels that each got.

#520 ci: update dockerfile and devdeps
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .github/workflows/test.yaml
  .nvmrc
  Dockerfile
  package.json
  pnpm-lock.yaml
Labels: dependencies, docker

#497 Do not allow logger and loggerInstance
  src/app.ts
Labels: automerge

#522 chore: update aws-sdk to patch GHSA-776f-qx25-q3cc
  package.json
  pnpm-lock.yaml
  test/minio.ts
Labels: security

#473 JWT authentication and authorization
  .dockerignore
  .env.example
  .gitignore
  docs/environment-variables.md
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/env.ts
  src/plugins/config.ts
  src/plugins/remote-cache/auth/index.ts
  src/plugins/remote-cache/auth/jwt.ts
  src/plugins/remote-cache/auth/static.ts
  src/plugins/remote-cache/index.ts
  src/plugins/remote-cache/routes/artifacts-events.ts
  src/plugins/remote-cache/routes/get-artifact.ts
  src/plugins/remote-cache/routes/get-status.ts
  src/plugins/remote-cache/routes/head-artifact.ts
  src/plugins/remote-cache/routes/put-artifact.ts
  test/google-cloud-storage.ts
  test/jwt-auth.ts
  test/minio.ts
  test/s3.ts
Labels: enhancement
